version: "3.7"
services:
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm.Dockerfile
      target: dev
    volumes:
      - ./src:/var/www/html
      - ci-writable:/var/www/html/writable
  web-server:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      target: dev
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  mysql-server:
    image: mysql:8.3
    restart: always
    ports:
      - '33006:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: platyplus2
    volumes:
      - mysql-data:/var/lib/mysql
  # Taken from https://github.com/vercel/next.js/blob/canary/examples/with-docker-multi-env/docker/development/Dockerfile
  front-server:
    build:
      context: .
      dockerfile: nextjs.Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
volumes:
  mysql-data:
    driver: local
  ci-writable:
    driver: local